login: &login
  adapter: postgresql
  host: localhost
  username: salva
  password:
  encoding: UTF-8

development:
  database: tuzo
  <<: *login

test:
  database: tuzo	
  <<: *login

production:
  database: tuzo
  <<: *login

