login: &login
  adapter: postgresql
  host: localhost
  username: salva
  password:
  encoding: UTF-8

development:
  database: tuzos
  <<: *login

test:
  database: tuzos	
  <<: *login

production:
  database: tuzos
  <<: *login

